lti1p3:
    key_chains:
        kid1:
            key_set_name: "platformSet"
            public_key: "file://%kernel.project_dir%/config/keys/public.key"
            private_key: "file://%kernel.project_dir%/config/keys/private.key"
            private_key_passphrase: ~
        kid2:
            key_set_name: "toolSet"
            public_key: "file://%kernel.project_dir%/config/keys/public.key"
            private_key: "file://%kernel.project_dir%/config/keys/private.key"
            private_key_passphrase: ~
        #
        # Necessary to integrate with TAO
        #
        kid3:
            key_set_name: "taoToolSet"
            public_key: "file://%kernel.project_dir%/config/keys/tao_public.key"
            private_key: ~ #"file://%kernel.project_dir%/config/keys/private.key"
            private_key_passphrase: ~
    platforms:
        localPlatform:
            name: "Local platform"
            audience: "http://localhost:8888/platform"
            oidc_authentication_url: "http://localhost:8888/lti1p3/oidc/login-authentication"
            oauth2_access_token_url: "http://demo_lti1p3_nginx/lti1p3/auth/kid1/token" # docker
        imsPlatform:
            name: "IMS platform"
            audience: "https://lti-ri.imsglobal.org"
            oidc_authentication_url: "https://lti-ri.imsglobal.org/platforms/978/authorizations/new"
            oauth2_access_token_url: "https://lti-ri.imsglobal.org/platforms/978/access_tokens"
        #
        # Necessary to integrate with TAO
        #
        taoPlatform:
            name: "TAO platform"
            audience: "https://test-tao-deploy.docker.localhost"
            oidc_authentication_url: "https://test-tao-deploy.docker.localhost/taoLti/Security/oidc"
            oauth2_access_token_url: "https://test-tao-deploy-nginx/taoLti/Security/oauth"

        #
        # Connect with Moodle
        #
        constructMoodlePlatform:
            name: "IMS platform"
            audience: "https://construct.moodlecloud.com"
            oidc_authentication_url: "https://construct.moodlecloud.com/mod/lti/auth.php"
            oauth2_access_token_url: "https://construct.moodlecloud.com/mod/lti/token.php"
    tools:
        localTool:
            name: "Local tool"
            audience: "http://localhost:8888/tool"
            oidc_login_initiation_url: "http://localhost:8888/lti1p3/oidc/login-initiation"
            launch_url: "http://localhost:8888/tool/launch"
            deep_link_launch_url: "http://localhost:8888/tool/deep-launch"
    registrations:
        local:
            client_id: "client_id"
            platform: "localPlatform"
            tool: "localTool"
            deployment_ids:
                - "deploymentId1"
                - "deploymentId2"
            platform_key_chain: "kid1"
            tool_key_chain: "kid2"
            platform_jwks_url: "http://localhost:8888/lti1p3/.well-known/jwks/platformSet.json"
            tool_jwks_url: "http://localhost:8888/lti1p3/.well-known/jwks/toolSet.json"
        imsPlatform:
            client_id: "ims_client_id"
            platform: "imsPlatform"
            tool: "localTool"
            deployment_ids:
                - "imsDeploymentId1"
            platform_key_chain: ~
            tool_key_chain: "kid2"
            platform_jwks_url: "https://lti-ri.imsglobal.org/platforms/978/platform_keys/986.json"
            tool_jwks_url: "http://localhost:8888/lti1p3/.well-known/jwks/toolSet.json"
        #
        # Necessary to integrate with TAO
        #
        taoPlatform:
            client_id: "client_id"
            platform: "taoPlatform"
            tool: "localTool"
            deployment_ids:
                - "42"
            platform_key_chain: ~ #"kid3"
            tool_key_chain: "kid2"
            platform_jwks_url: "http://test-tao-deploy-nginx/taoLti/Security/jwks"
            tool_jwks_url: "http://localhost:8888/lti1p3/.well-known/jwks/toolSet.json"

        #
        # Connect with Moodle
        #
        constructMoodlePlatform:
            client_id: "YK4O7vHC6E7JFk8"
            platform: "constructMoodlePlatform"
            tool: "localTool"
            deployment_ids:
                - "1"
            platform_key_chain: ~
            tool_key_chain: "kid2"
            platform_jwks_url: "https://construct.moodlecloud.com/mod/lti/certs.php"
            tool_jwks_url: "http://localhost:8888/lti1p3/.well-known/jwks/toolSet.json"
