lti1p3:
    scopes:
        - 'https://purl.imsglobal.org/spec/lti-nrps/scope/contextmembership.readonly'
        - 'https://purl.imsglobal.org/spec/lti-bo/scope/basicoutcome'
        - 'https://purl.imsglobal.org/spec/lti-ags/scope/score'
        - 'https://purl.imsglobal.org/spec/lti-ap/scope/control.all'
    key_chains:
        platformKey:
            key_set_name: "platformSet"
            public_key: "file://%kernel.project_dir%/config/keys/public.key"
            private_key: "file://%kernel.project_dir%/config/keys/private.key"
            private_key_passphrase: ~
#        toolKey:
#            key_set_name: "toolSet"
#            public_key: "file://%kernel.project_dir%/config/keys/tool/public.key"
#            private_key: "file://%kernel.project_dir%/config/keys/tool/private.key"
#            private_key_passphrase: ~
    platforms:
        local:
            name: "Demo LTI 1.3 platform"
            audience: "https://sds-demo-lti1p3.docker.localhost/platform"
            oidc_authentication_url: "https://sds-demo-lti1p3.docker.localhost/lti1p3/oidc/authentication"
            oauth2_access_token_url: "https://sds-demo-lti1p3.docker.localhost/lti1p3/auth/platformKey/token"
    tools:
        ms:
            name: "Manual Scoring tool"
            audience: "https://sds-manual-scoring-be.docker.localhost/tool"
            oidc_initiation_url: "https://sds-manual-scoring-be.docker.localhost/lti1p3/oidc/initiation"
            launch_url: "https://sds-manual-scoring-be.docker.localhost/api/v1/auth/lti1p3/launch"
            deep_linking_url: null
    registrations:
        ms:
            client_id: "client_id"
            platform: "local"
            tool: "ms"
            deployment_ids:
                - "deploymentId1"
            platform_key_chain: "platformKey"
            tool_key_chain: null
            platform_jwks_url: null
            tool_jwks_url: "http://sds-manual-scoring-be.docker.localhost/lti1p3/.well-known/jwks/toolSet.json"
