security:
    providers:
        users_in_memory: { memory: null }
    firewalls:
        tool_message_area:
            pattern: ^/tool/launch
            stateless: true
            lti1p3_message_tool: true
        platform_message_area:
            pattern: ^/platform/message/deep-linking-return
            stateless: true
            lti1p3_message_platform: true
        platform_service_ags_area:
            pattern: ^/platform/service/ags
            stateless: true
            lti1p3_service: {
                scopes: [
                        'https://purl.imsglobal.org/spec/lti-ags/scope/lineitem',
                        'https://purl.imsglobal.org/spec/lti-ags/scope/lineitem.readonly',
                        'https://purl.imsglobal.org/spec/lti-ags/scope/result.readonly',
                        'https://purl.imsglobal.org/spec/lti-ags/scope/score'
                ]
            }
        platform_service_basic_outcome_area:
            pattern: ^/platform/service/basic-outcome
            stateless: true
            lti1p3_service: {
                scopes: [
                        'https://purl.imsglobal.org/spec/lti-bo/scope/basicoutcome'
                ]
            }
        platform_service_nrps_area:
            pattern: ^/platform/service/nrps
            stateless: true
            lti1p3_service: {
                scopes: [
                    'https://purl.imsglobal.org/spec/lti-nrps/scope/contextmembership.readonly'
                ]
            }
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: users_in_memory

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
