version: '3'

services:
    demo_lti1p3_nginx:
        container_name: demo_lti1p3_nginx
        image: nginx:stable
        networks:
            - demo_lti1p3_network
        ports:
            - "80:80"
            - "443:443"
        expose:
          - 80
          - 443
        volumes:
            - .:/var/www/html:cached
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
            - /etc/letsencrypt/live/lti.showcase.gcp.taocloud.org/fullchain.pem:/etc/nginx/certs/fullchain.pem
            - /etc/letsencrypt/live/lti.showcase.gcp.taocloud.org/privkey.pem:/etc/nginx/certs/privkey.pem
        working_dir: /etc/nginx/conf.d

    demo_lti1p3_phpfpm:
        container_name: demo_lti1p3_phpfpm
        build:
            context: ./docker/phpfpm
        expose:
            - 9000
        networks:
            - demo_lti1p3_network
        volumes:
            - .:/var/www/html:cached
        working_dir: /var/www/html

    demo_lti1p3_redis:
        container_name: demo_lti1p3_redis
        image: redis:latest
        command: ["redis-server", "--appendonly", "yes"]
        hostname: demo_lti1p3_redis
        networks:
            - demo_lti1p3_network
        ports:
            - "6379:6379"
        volumes:
            - demo_lti1p3_redis_volume:/data

    demo_lti1p3_redis_commander:
        container_name: demo_lti1p3_redis_commander
        image: rediscommander/redis-commander:latest
        hostname: demo_lti1p3_redis_commander
        networks:
            - demo_lti1p3_network
        ports:
            - "8081:8081"
        expose:
            - 8081
        environment:
            - REDIS_HOSTS=local:demo_lti1p3_redis:6379
            - READ_ONLY=true

volumes:
    demo_lti1p3_redis_volume:
        driver: local

networks:
    demo_lti1p3_network:
        driver: bridge
