home:
    path: /
    controller: App\Action\HomeAction

platform_message_launch_lti_resource_link:
    path: /platform/message/launch/lti-resource-link
    controller: App\Action\Platform\Message\LtiResourceLinkLaunchAction

platform_message_launch_deep_linking:
    path: /platform/message/launch/deep-linking
    controller: App\Action\Platform\Message\DeepLinkingLaunchAction

platform_message_deep_linking_return:
    path: /platform/message/deep-linking-return
    controller: App\Action\Platform\Message\DeepLinkingReturnAction

tool_message_launch:
    path: /tool/launch
    controller: App\Action\Tool\Message\LtiResourceLinkLaunchAction

tool_message_deep_linking:
    path: /tool/launch/deep-linking
    controller: App\Action\Tool\Message\DeepLinkingLaunchAction

tool_message_deep_linking_response:
    methods: [POST]
    path: /tool/deep-linking-response
    controller: App\Action\Tool\Message\DeepLinkingResponseAction

tool_service_client:
    path: /tool/service/client
    controller: App\Action\Tool\Service\LtiServiceClientAction

tool_ajax_service_nrps:
    path: /tool/ajax/nrps
    controller: App\Action\Tool\Ajax\NrpsServiceClientAction
    condition: "request.isXmlHttpRequest()"

platform_nrps_memberships:
    methods: [GET]
    path: /platform/service/nrps/memberships
    controller: App\Action\Platform\Service\Nrps\MembershipAction

platform_ags_list_scores:
    methods: [GET]
    path: /platform/service/ags-list-scores
    controller: App\Action\Platform\Service\Ags\HomeAction

platform_ags_delete_scores:
    methods: [GET]
    path: /platform/service/ags-delete-scores
    controller: App\Action\Platform\Service\Ags\DeleteScoresAction

platform_ags_create_score:
    methods: [POST]
    path: /platform/service/ags/{contextId}/lineitems/{lineItemId}/scores
    controller: App\Action\Platform\Service\Ags\CreateScoreAction
