home:
    path: /
    controller: App\Action\HomeAction

platform_message_link:
    path: /platform/message/link
    controller: App\Action\Platform\Message\LtiLinkAction

tool_message_launch:
    path: /tool/launch
    controller: App\Action\Tool\Message\LtiLaunchAction

tool_service_client:
    path: /tool/service/client
    controller: App\Action\Tool\Service\LtiServiceClientAction

tool_ajax_service_nrps:
    path: /tool/ajax/nrps
    controller: App\Action\Tool\Ajax\NrpsServiceClientAction
    condition: "request.isXmlHttpRequest()"

platform_ags_list_scores:
    methods: [GET]
    path: /platform/service/ags-list-scores
    controller: App\Action\Platform\Service\Ags\HomeAction

platform_ags_delete_scores:
    methods: [GET]
    path: /platform/service/ags-delete-scores
    controller: App\Action\Platform\Service\Ags\DeleteScoresAction

platform_ags_create_score:
    methods: [POST]
    path: /platform/service/ags/{contextId}/lineitems/{lineItemId}/scores
    controller: App\Action\Platform\Service\Ags\CreateScoreAction
