imports:
    - { resource: 'demo/claims.yaml' }
    - { resource: 'demo/deep_linking.yaml' }
    - { resource: 'demo/users.yaml' }

parameters:
    application_host: '%env(resolve:APP_HOST)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Action\:
        resource: '../src/Action'
        tags: ['controller.service_arguments']

    OAT\Library\Lti1p3Core\Security\User\UserAuthenticatorInterface:
        class: App\Security\User\UserAuthenticator

    OAT\Library\Lti1p3Core\User\UserIdentityFactoryInterface:
        class: OAT\Library\Lti1p3Core\User\UserIdentityFactory

    OAT\Library\Lti1p3DeepLinking\Message\Launch\Builder\DeepLinkingLaunchRequestBuilder: ~

    OAT\Library\Lti1p3DeepLinking\Message\Launch\Builder\DeepLinkingLaunchResponseBuilder: ~

    OAT\Library\Lti1p3DeepLinking\Factory\ResourceCollectionFactoryInterface:
        class: OAT\Library\Lti1p3DeepLinking\Factory\ResourceCollectionFactory

    OAT\Library\Lti1p3Nrps\Service\Client\MembershipServiceClient: ~

    OAT\Library\Lti1p3BasicOutcome\Service\Client\BasicOutcomeServiceClient: ~

    OAT\Library\Lti1p3BasicOutcome\Service\Server\Handler\BasicOutcomeServiceServerHandler: ~

    OAT\Library\Lti1p3BasicOutcome\Serializer\Request\BasicOutcomeRequestSerializerInterface:
        class: OAT\Library\Lti1p3BasicOutcome\Serializer\Request\BasicOutcomeRequestSerializer

    OAT\Library\Lti1p3BasicOutcome\Serializer\Response\BasicOutcomeResponseSerializerInterface:
        class: OAT\Library\Lti1p3BasicOutcome\Serializer\Response\BasicOutcomeResponseSerializer

    OAT\Library\Lti1p3BasicOutcome\Service\Server\Processor\BasicOutcomeServiceServerProcessorInterface:
        class: App\BasicOutcome\BasicOutcomeProcessor
