imports:
    - { resource: 'demo/claims.yaml' }
    - { resource: 'demo/deep_linking.yaml' }
    - { resource: 'demo/users.yaml' }

parameters:
    application_host: '%env(resolve:APP_HOST)%'
    application_version: '1.9.0'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Action\:
        resource: '../src/Action'
        tags: ['controller.service_arguments']

    # LTI core dependencies

    OAT\Library\Lti1p3Core\Security\User\UserAuthenticatorInterface:
        class: App\Security\User\UserAuthenticator

    OAT\Library\Lti1p3Core\User\UserIdentityFactoryInterface:
        class: OAT\Library\Lti1p3Core\User\UserIdentityFactory

    # LTI AGS dependencies

    OAT\Library\Lti1p3Ags\Service\LineItem\Server\Handler\ListLineItemServiceServerRequestHandler:
        arguments:
            - '@App\Ags\LineItemRepository'

    # LTI basic outcome dependencies

    OAT\Library\Lti1p3BasicOutcome\Service\Server\Handler\BasicOutcomeServiceServerRequestHandler:
        arguments:
            - '@App\BasicOutcome\BasicOutcomeProcessor'

    OAT\Library\Lti1p3BasicOutcome\Service\Client\BasicOutcomeServiceClient: ~

    # LTI deep linking dependencies

    OAT\Library\Lti1p3DeepLinking\Message\Launch\Builder\DeepLinkingLaunchRequestBuilder: ~

    OAT\Library\Lti1p3DeepLinking\Message\Launch\Builder\DeepLinkingLaunchResponseBuilder: ~

    OAT\Library\Lti1p3DeepLinking\Factory\ResourceCollectionFactoryInterface:
        class: OAT\Library\Lti1p3DeepLinking\Factory\ResourceCollectionFactory

    # LTI NRPS dependencies

    OAT\Library\Lti1p3Nrps\Service\Server\Handler\MembershipServiceServerRequestHandler:
        arguments:
            - '@App\Nrps\MembershipServiceServerBuilder'

    OAT\Library\Lti1p3Nrps\Service\Client\MembershipServiceClient: ~

    OAT\Library\Lti1p3Nrps\Factory\Member\MemberFactoryInterface:
        class: OAT\Library\Lti1p3Nrps\Factory\Member\MemberFactory
